version: '3'
services:

  postgres-operator:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=egendata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgresuser -d egendata"]
      interval: 10s
      timeout: 5s
      retries: 5
